# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 2

[battery]
discharging_symbol = '💀 '
charging_symbol = "⚡ "

[[battery.display]]  # "bold red" style and discharging_symbol when capacity is between 0% and 10%
threshold = 20
style = "bold red"

[[battery.display]]  # "bold yellow" style and 💦 symbol when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[package]
disabled = true